# Generates deploy/.env with cryptographically random secrets.
# Idempotent: refuses to overwrite an existing .env unless -Force is passed.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\bootstrap.ps1
#   docker compose up -d
#
# NOTE: this file is deliberately ASCII-only. Windows PowerShell 5.1 reads .ps1 files
# without a BOM as ANSI, so any non-ASCII character (em dash, smart quote) is mangled
# into mojibake and can break parsing. Keep it that way.
#
# The generated .env is written UTF-8 WITHOUT a BOM on purpose: PowerShell 5.1's default
# UTF-8 emits a BOM, and docker compose would fold it into the first variable name.

[CmdletBinding()]
param([switch]$Force)

$ErrorActionPreference = 'Stop'
$envPath = Join-Path $PSScriptRoot '.env'

if ((Test-Path $envPath) -and (-not $Force)) {
    Write-Host "deploy/.env already exists. Re-run with -Force to regenerate." -ForegroundColor Yellow
    Write-Host "Regenerating invalidates LANGFUSE_ENCRYPTION_KEY, making existing traces unreadable."
    exit 0
}

function New-Hex {
    param([int]$Bytes)
    $buf = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($buf) } finally { $rng.Dispose() }
    -join ($buf | ForEach-Object { $_.ToString('x2') })
}

$content = @"
# Generated by deploy/bootstrap.ps1 - DO NOT COMMIT.

# --- core: System DB registries ---
EXTRCT_DB_USER=extrct
EXTRCT_DB_PASSWORD=$(New-Hex 24)
EXTRCT_DB_NAME=extrct

# --- core: Label Studio ---
LABEL_STUDIO_USERNAME=admin@extrct.local
LABEL_STUDIO_PASSWORD=$(New-Hex 16)

# --- Langfuse ---
NEXTAUTH_URL=http://localhost:3000
LANGFUSE_NEXTAUTH_SECRET=$(New-Hex 32)
LANGFUSE_SALT=$(New-Hex 32)
LANGFUSE_ENCRYPTION_KEY=$(New-Hex 32)
LANGFUSE_DB_PASSWORD=$(New-Hex 24)
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=$(New-Hex 24)
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=$(New-Hex 24)
REDIS_AUTH=$(New-Hex 24)

# --- Langflow (prototype profile) ---
LANGFLOW_SUPERUSER=admin
LANGFLOW_SUPERUSER_PASSWORD=$(New-Hex 16)
LANGFLOW_DB_PASSWORD=$(New-Hex 24)

# Fill in after creating a project in the Langfuse UI, then restart Langflow.
LANGFUSE_PUBLIC_KEY=
LANGFUSE_SECRET_KEY=
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($envPath, $content, $utf8NoBom)

Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host ""
Write-Host "Your logins (also stored in deploy/.env):"
$lines = Get-Content $envPath
foreach ($key in 'LABEL_STUDIO_USERNAME','LABEL_STUDIO_PASSWORD','LANGFLOW_SUPERUSER','LANGFLOW_SUPERUSER_PASSWORD') {
    $match = $lines | Where-Object { $_ -like "$key=*" }
    Write-Host ("  " + $match)
}
Write-Host ""
Write-Host "Next: docker compose up -d"
